
///// THE MODEL COMPILES BUT DOES NOT SIMULATE BECAUSE OF 
///// MISSING INPUT VALUE FOR SOME BLOCK VARIABLES

package Inputs
  extends Physiolibrary.Types.IO_Bus;
  redeclare model extends Variables
    //CardioVascular
    T.Concentration ctHb(varName="ctHb", k=8.4); 
    T.Fraction BloodVol_Hct(varName="BloodVol.Hct", k=0.44);
    T.Concentration ctHb_ery(varName="ctHb_ery", k=21);
    //Gases
    T.Fraction bone_sO2(varName="bone_sO2");
    T.Fraction brain_sO2(varName="brain_sO2");
    T.Fraction fat_sO2(varName="fat_sO2");
    T.Fraction GITract_sO2(varName="GITract_sO2");
    T.Fraction kidney_sO2(varName="kidney_sO2");
    T.Fraction leftHeart_sO2(varName="leftHeart_sO2");
    T.Fraction liver_sO2(varName="liver_sO2");
    T.Fraction O2Artys_sO2(varName="O2Artys_sO2");
    T.Fraction O2Lung_sO2(varName="O2Lung_sO2");
    T.Fraction O2Veins_sO2(varName="O2Veins_sO2");
    T.Fraction otherTissue_sO2(varName="otherTissue_sO2");
    T.Fraction respiratoryMuscle_sO2(varName="respiratoryMuscle_sO2");
    T.Fraction rightHeart_sO2(varName="rightHeart_sO2");
    T.Fraction skeletalMuscle_sO2(varName="skeletalMuscle_sO2");
    T.Fraction skin_sO2(varName="skin_sO2");
    T.Concentration CO2Artys_cHCO3(varName="CO2Artys.[HCO3(mEq/L)]", k=24);
    T.Concentration CO2Lungs_cHCO3(varName="LungCO2.[Capy]", storeUnit="mol/l", k=23.9886);
    T.Concentration bone_cHCO3(varName="Bone-CO2.[BloodHCO3(mEq/L)]");
    T.Concentration brain_cHCO3(varName="Brain-CO2.[BloodHCO3(mEq/L)]");
    T.Concentration fat_cHCO3(varName="Fat-CO2.[BloodHCO3(mEq/L)]");
    T.Concentration GITract_cHCO3(varName="GITract-CO2.[BloodHCO3(mEq/L)]");
    T.Concentration kidney_cHCO3(varName="Kidney-CO2.[BloodHCO3(mEq/L)]");
    T.Concentration leftHeart_cHCO3(varName="LeftHeart-CO2.[BloodHCO3(mEq/L)]");
    T.Concentration liver_cHCO3(varName="Liver-CO2.[BloodHCO3(mEq/L)]");
    T.Concentration otherTissue_cHCO3(varName="OtherTissue-CO2.[BloodHCO3(mEq/L)]");
    T.Concentration respiratoryMuscle_cHCO3(varName="RespiratoryMuscle-CO2.[BloodHCO3(mEq/L)]");
    T.Concentration rightHeart_cHCO3(varName="RightHeart-CO2.[BloodHCO3(mEq/L)]");
    T.Concentration skeletalMuscle_cHCO3(varName="SkeletalMuscle-CO2.[BloodHCO3(mEq/L)]");
    T.Concentration skin_cHCO3(varName="Skin-CO2.[BloodHCO3(mEq/L)]");
    T.Pressure bone_pCO2(varName="Bone-CO2.PCO2");
    T.Pressure brain_pCO2(varName="Brain-CO2.PCO2");
    T.Pressure fat_pCO2(varName="Fat-CO2.PCO2");
    T.Pressure GITract_pCO2(varName="GITract-CO2.PCO2");
    T.Pressure kidney_pCO2(varName="Kidney-CO2.PCO2");
    T.Pressure leftHeart_pCO2(varName="LeftHeart-CO2.PCO2");
    T.Pressure liver_pCO2(varName="Liver-CO2.PCO2");
    T.Pressure otherTissue_pCO2(varName="OtherTissue-CO2.PCO2");
    T.Pressure respiratoryMuscle_pCO2(varName="RespiratoryMuscle-CO2.PCO2");
    T.Pressure rightHeart_pCO2(varName="RightHeart-CO2.PCO2");
    T.Pressure skeletalMuscle_pCO2(varName="SkeletalMuscle-CO2.PCO2");
    T.Pressure skin_pCO2(varName="Skin-CO2.PCO2");
    T.Pressure CO2Artys_pCO2(varName="CO2Artys.Pressure");
    T.Concentration GITract_cHCO3_interstitial(varName="GITract-CO2.[HCO3(mEq/L)]");
    T.Concentration bone_cHCO3_interstitial(varName="Bone-CO2.[HCO3(mEq/L)]");
    T.Concentration brain_cHCO3_interstitial(varName="Brain-CO2.[HCO3(mEq/L)]");
    T.Concentration fat_cHCO3_interstitial(varName="Fat-CO2.[HCO3(mEq/L)]");
    T.Concentration kidney_cHCO3_interstitial(varName="Kidney-CO2.[HCO3(mEq/L)]");
    T.Concentration leftHeart_cHCO3_interstitial(varName="LeftHeart-CO2.[HCO3(mEq/L)]");
    T.Concentration liver_cHCO3_interstitial(varName="Liver-CO2.[HCO3(mEq/L)]");
    T.Concentration otherTissue_cHCO3_interstitial(varName="OtherTissue-CO2.[HCO3(mEq/L)]");
    T.Concentration respiratoryMuscle_cHCO3_interstitial(varName="RespiratoryMuscle-CO2.[HCO3(mEq/L)]");
    T.Concentration rightHeart_cHCO3_interstitial(varName="RightHeart-CO2.[HCO3(mEq/L)]");
    T.Concentration skeletalMuscle_cHCO3_interstitial(varName="SkeletalMuscle-CO2.[HCO3(mEq/L)]");
    T.Concentration skin_cHCO3_interstitial(varName="Skin-CO2.[HCO3(mEq/L)]");
    //Heat
    T.Temperature bone_T(varName="HeatCore.Temp(C)");
    T.Temperature brain_T(varName="HeatCore.Temp(C)");
    T.Temperature fat_T(varName="HeatCore.Temp(C)");
    T.Temperature GITract_T(varName="HeatCore.Temp(C)");
    T.Temperature kidney_T(varName="HeatCore.Temp(C)");
    T.Temperature leftHeart_T(varName="HeatCore.Temp(C)");
    T.Temperature liver_T(varName="HeatCore.Temp(C)");
    T.Temperature otherTissue_T(varName="HeatCore.Temp(C)");
    T.Temperature respiratoryMuscle_T(varName="HeatCore.Temp(C)");
    T.Temperature rightHeart_T(varName="HeatCore.Temp(C)");
    T.Temperature skeletalMuscle_T(varName="HeatCore.Temp(C)");
    T.Temperature skin_T(varName="HeatCore.Temp(C)");
    T.Temperature HeatCore_Temp(varName="HeatCore.Temp(C)");
    //Proteins
    T.Concentration ctAlb(varName="ctAlb", k=0.66);
    T.Concentration CO2Veins_cHCO3(varName="CO2Veins.[HCO3(mEq/L)]", k=25.6);
    T.MassConcentration ctGlb(varName="ctGlb", storeUnit="g/l", k=28);
    //Water
    T.VolumeFlowRate CD_H2O_Outflow(varName="CD_H2O.Outflow", k=1.2982e-008);
    //Metabolism
    T.Concentration bone_cLactate(varName="Bone-Lactate.[Lac-(mEq/L)]");
    T.Concentration brain_cLactate(varName="Brain-Lactate.[Lac-(mEq/L)]");
    T.Concentration fat_cLactate(varName="Fat-Lactate.[Lac-(mEq/L)]");
    T.Concentration GITract_cLactate(varName="GITract-Lactate.[Lac-(mEq/L)]");
    T.Concentration kidney_cLactate(varName="Kidney-Lactate.[Lac-(mEq/L)]");
    T.Concentration leftHeart_cLactate(varName="LeftHeart-Lactate.[Lac-(mEq/L)]");
    T.Concentration liver_cLactate(varName="Liver-Lactate.[Lac-(mEq/L)]");
    T.Concentration otherTissue_cLactate(varName="OtherTissue-Lactate.[Lac-(mEq/L)]");
    T.Concentration respiratoryMuscle_cLactate(varName="RespiratoryMuscle-Lactate.[Lac-(mEq/L)]");
    T.Concentration rightHeart_cLactate(varName="RightHeart-Lactate.[Lac-(mEq/L)]");
    T.Concentration skeletalMuscle_cLactate(varName="SkeletalMuscle-Lactate.[Lac-(mEq/L)]");
    T.Concentration skin_cLactate(varName="Skin-Lactate.[Lac-(mEq/L)]");

    T.Concentration LacPool_Lac_mEq_per_litre(varName="LacPool.[Lac-(mEq/L)]");
    //Electrolytes
    T.MolarFlowRate CD_Na_Outflow(varName="CD_Na.Outflow", k=2.09015e-006);
    T.MolarFlowRate CD_NH4_Outflow(varName="CD_NH4.Outflow", k=4.69907e-007);
    T.MolarFlowRate CD_K_Outflow(varName="CD_K.Outflow", k=8.95573e-007);
    T.MolarFlowRate CD_KA_Outflow(varName="CD_KA.Outflow", storeUnit="mmol/min", k=0);
    T.MolarFlowRate CD_SO4_Outflow(varName="CD_SO4_Outflow", k=3.16945e-007);
    T.MolarFlowRate CD_PO4_Outflow(varName="CD_PO4.Outflow", k=3.84862e-007);
    T.MolarFlowRate CD_Cl_Outflow(varName="CD_Cl.Outflow");
    T.MolarFlowRate CD_Mg_Outflow(varName="CD_Mg.Outflow");
    T.MolarFlowRate CD_Ca_Outflow(varName="CD_Ca.Outflow");
    Physiolibrary.Types.Constants.DeprecatedUntypedConstant PTH1(k=16.8/14);
    Physiolibrary.Types.Constants.DeprecatedUntypedConstant blood_SID(k=0);
    T.Concentration KCell_conc(varName="KCell.[K+(mEq/L)]");
  equation
    connect(ctAlb.y, busConnector.ctAlb);
    connect(CO2Artys_cHCO3.y, busConnector.CO2Artys_cHCO3);
    connect(CO2Veins_cHCO3.y, busConnector.CO2Veins_cHCO3);
    connect(ctGlb.y, busConnector.ctGlb);
    connect(PTH1.y, busConnector.ctPO4);
    connect(CO2Lungs_cHCO3.y, busConnector.CO2Lung_cHCO3);
    connect(ctHb.y, busConnector.ctHb);
    connect(bone_sO2.y, busConnector.bone_sO2);
    connect(brain_sO2.y, busConnector.brain_sO2);
    connect(fat_sO2.y, busConnector.fat_sO2);
    connect(GITract_sO2.y, busConnector.GITract_sO2);
    connect(kidney_sO2.y, busConnector.kidney_sO2);
    connect(leftHeart_sO2.y, busConnector.leftHeart_sO2);
    connect(liver_sO2.y, busConnector.liver_sO2);
    connect(O2Artys_sO2.y, busConnector.O2Artys_sO2);
    connect(O2Veins_sO2.y, busConnector.O2Veins_sO2);
    connect(otherTissue_sO2.y, busConnector.otherTissue_sO2);
    connect(respiratoryMuscle_sO2.y, busConnector.respiratoryMuscle_sO2);
    connect(rightHeart_sO2.y, busConnector.rightHeart_sO2);
    connect(skeletalMuscle_sO2.y, busConnector.skeletalMuscle_sO2);
    connect(skin_sO2.y, busConnector.skin_sO2);
    connect(O2Lung_sO2.y, busConnector.O2Lung_sO2);
    connect(bone_T.y, busConnector.bone_T);
    connect(brain_T.y, busConnector.brain_T);
    connect(fat_T.y, busConnector.fat_T);
    connect(GITract_T.y, busConnector.GITract_T);
    connect(kidney_T.y, busConnector.kidney_T);
    connect(leftHeart_T.y, busConnector.leftHeart_T);
    connect(liver_T.y, busConnector.liver_T);
    connect(otherTissue_T.y, busConnector.otherTissue_T);
    connect(respiratoryMuscle_T.y, busConnector.respiratoryMuscle_T);
    connect(rightHeart_T.y, busConnector.rightHeart_T);
    connect(skeletalMuscle_T.y, busConnector.skeletalMuscle_T);
    connect(skin_T.y, busConnector.skin_T);
    connect(bone_cLactate.y, busConnector.bone_cLactate);
    connect(brain_cLactate.y, busConnector.brain_cLactate);
    connect(fat_cLactate.y, busConnector.fat_cLactate);
    connect(GITract_cLactate.y, busConnector.GITract_cLactate);
    connect(kidney_cLactate.y, busConnector.kidney_cLactate);
    connect(leftHeart_cLactate.y, busConnector.leftHeart_cLactate);
    connect(liver_cLactate.y, busConnector.liver_cLactate);
    connect(otherTissue_cLactate.y, busConnector.otherTissue_cLactate);
    connect(respiratoryMuscle_cLactate.y, busConnector.respiratoryMuscle_cLactate);
    connect(rightHeart_cLactate.y, busConnector.rightHeart_cLactate);
    connect(skeletalMuscle_cLactate.y, busConnector.skeletalMuscle_cLactate);
    connect(skin_cLactate.y, busConnector.skin_cLactate);
    connect(bone_cHCO3.y, busConnector.bone_cHCO3);
    connect(brain_cHCO3.y, busConnector.brain_cHCO3);
    connect(fat_cHCO3.y, busConnector.fat_cHCO3);
    connect(GITract_cHCO3.y, busConnector.GITract_cHCO3);
    connect(kidney_cHCO3.y, busConnector.kidney_cHCO3);
    connect(leftHeart_cHCO3.y, busConnector.leftHeart_cHCO3);
    connect(liver_cHCO3.y, busConnector.liver_cHCO3);
    connect(otherTissue_cHCO3.y, busConnector.otherTissue_cHCO3);
    connect(respiratoryMuscle_cHCO3.y, busConnector.respiratoryMuscle_cHCO3);
    connect(rightHeart_cHCO3.y, busConnector.rightHeart_cHCO3);
    connect(skeletalMuscle_cHCO3.y, busConnector.skeletalMuscle_cHCO3);
    connect(skin_cHCO3.y, busConnector.skin_cHCO3);
    connect(bone_pCO2.y, busConnector.bone_pCO2);
    connect(brain_pCO2.y, busConnector.brain_pCO2);
    connect(fat_pCO2.y, busConnector.fat_pCO2);
    connect(GITract_pCO2.y, busConnector.gitract_pCO2);
    connect(kidney_pCO2.y, busConnector.kidney_pCO2);
    connect(leftHeart_pCO2.y, busConnector.leftHeart_pCO2);
    connect(liver_pCO2.y, busConnector.liver_pCO2);
    connect(otherTissue_pCO2.y, busConnector.otherTissue_pCO2);
    connect(respiratoryMuscle_pCO2.y, busConnector.respiratoryMuscle_pCO2);
    connect(rightHeart_pCO2.y, busConnector.rightHeart_pCO2);
    connect(skeletalMuscle_pCO2.y, busConnector.skeletalMuscle_pCO2);
    connect(skin_pCO2.y, busConnector.skin_pCO2);
    connect(bone_cHCO3_interstitial.y, busConnector.bone_cHCO3_interstitial);
    connect(brain_cHCO3_interstitial.y, busConnector.brain_cHCO3_interstitial);
    connect(fat_cHCO3_interstitial.y, busConnector.fat_cHCO3_interstitial);
    connect(GITract_cHCO3_interstitial.y, busConnector.GITract_cHCO3_interstitial);
    connect(kidney_cHCO3_interstitial.y, busConnector.kidney_cHCO3_interstitial);
    connect(leftHeart_cHCO3_interstitial.y, busConnector.leftHeart_cHCO3_interstitial);
    connect(liver_cHCO3_interstitial.y, busConnector.liver_cHCO3_interstitial);
    connect(otherTissue_cHCO3_interstitial.y, busConnector.otherTissue_cHCO3_interstitial);
    connect(respiratoryMuscle_cHCO3_interstitial.y, busConnector.respiratoryMuscle_cHCO3_interstitial);
    connect(rightHeart_cHCO3_interstitial.y, busConnector.rightHeart_cHCO3_interstitial);
    connect(skeletalMuscle_cHCO3_interstitial.y, busConnector.skeletalMuscle_cHCO3_interstitial);
    connect(skin_cHCO3_interstitial.y, busConnector.skin_cHCO3_interstitial);
    connect(LacPool_Lac_mEq_per_litre.y, busConnector.LacPool);
    connect(KCell_conc.y, busConnector.KCell_conc);
    connect(BloodVol_Hct.y, busConnector.BloodVol_Hct);
    connect(HeatCore_Temp.y, busConnector.HeatCore_Temp);
    connect(ctHb_ery.y, busConnector.ctHb_ery);
    connect(CD_Na_Outflow.y, busConnector.CD_Na_Outflow);
    connect(CD_NH4_Outflow.y, busConnector.CD_NH4_Outflow);
    connect(CD_K_Outflow.y, busConnector.CD_K_Outflow);
    connect(CD_SO4_Outflow.y, busConnector.CD_SO4_Outflow);
    connect(CD_KA_Outflow.y, busConnector.CD_KA_Outflow);
    connect(CD_PO4_Outflow.y, busConnector.CD_PO4_Outflow);
    connect(CD_Cl_Outflow.y, busConnector.CD_Cl_Outflow);
    connect(CD_Mg_Outflow.y, busConnector.CD_Mg_Outflow);
    connect(CD_Ca_Outflow.y, busConnector.CD_Ca_Outflow);
    connect(CO2Artys_pCO2.y, busConnector.CO2Artys_pCO2);
    connect(CD_H2O_Outflow.y, busConnector.CD_H2O_Outflow);
    connect(blood_SID.y, busConnector.Blood_SID);
  end Variables;
end Inputs;

model Test  
  Physiolibrary.Types.BusConnector busConnector;
  Physiomodel.Electrolytes.AcidBase.AcidBase acidBase;
  Inputs.Input inputs;
equation
  connect(inputs.busConnector, busConnector);
  connect(busConnector, acidBase.busConnector);
end Test;
