package Inputs
  extends Physiolibrary.Types.IO_Bus;
  redeclare model extends Variables
    //CardioVascularSystem
    T.VolumeFlowRate CardiacOutput(varName="CardiacOutput.Flow", k=9.17342e-005);
    T.VolumeFlowRate AlveolarVentilated_BloodFlow(varName="LungBloodFlow.AlveolarVentilated", k=8.98333e-005);
    T.Fraction BloodVol_Hct(varName="BloodVol.Hct", k=0.44);
    T.Volume ArtysVol(varName="ArtysVol.Vol", k=0.0015985);
    T.Volume VeinsVol(varName="VeinsVol.Vol", k=0.00379513);
    T.VolumeFlowRate bone_BloodFlow(varName="Bone-Flow.BloodFlow", k=5.40143e-006);
    T.VolumeFlowRate brain_BloodFlow(varName="Brain-Flow.BloodFlow", k=1.36172e-005);
    T.VolumeFlowRate fat_BloodFlow(varName="Fat-Flow.BloodFlow", k=4.01915e-006);
    T.VolumeFlowRate GITract_BloodFlow(varName="GITract-Flow.BloodFlow", k=1.9228e-005);
    T.VolumeFlowRate kidney_BloodFlow(varName="Kidney-Flow.BloodFlow", k=2.07108e-005);
    T.VolumeFlowRate leftHeart_BloodFlow(varName="LeftHeart-Flow.BloodFlow", k=3.76667e-006);
    T.VolumeFlowRate otherTissue_BloodFlow(varName="OtherTissue-Flow.BloodFlow", k=6.25202e-006);
    T.VolumeFlowRate respiratoryMuscle_BloodFlow(varName="RespiratoryMuscle-Flow.BloodFlow", k=1.63743e-006);
    T.VolumeFlowRate rightHeart_BloodFlow(varName="RightHeart-Flow.BloodFlow", k=7.08333e-007);
    T.VolumeFlowRate skeletalMuscle_BloodFlow(varName="SkeletalMuscle-Flow.BloodFlow", k=1.072e-005);
    T.VolumeFlowRate skin_BloodFlow(varName="Skin-Flow.BloodFlow", k=2.68538e-006);
    T.VolumeFlowRate HepaticArty_BloodFlow(varName="HepaticArty.Flow", k=4.10747e-006);
    //Gases
    T.Fraction O2Lung_sO2(varName="O2Lung_sO2", k=0.9389);
    T.Fraction O2Veins_sO2(varName="O2Veins_sO2", k=0.735709);
    T.Fraction O2Artys_sO2(varName="O2Artys_sO2", k=0.92);
    T.VolumeFlowRate AlveolarVentilation_Env(varName="AlveolarVentilation_Env", k=6.28222e-005);
    T.Fraction bone_sO2(varName="bone_sO2", k=0.694079);
    T.Fraction brain_sO2(varName="brain_sO2", k=0.675702);
    T.Fraction fat_sO2(varName="fat_sO2", k=0.835473);
    T.Fraction GITract_sO2(varName="GITract_sO2", k=0.840316);
    T.Fraction kidney_sO2(varName="kidney_sO2", k=0.83);
    T.Fraction leftHeart_sO2(varName="leftHeart_sO2", k=0.177171);
    T.Fraction liver_sO2(varName="liver_sO2", k=0.28643);
    T.Fraction otherTissue_sO2(varName="otherTissue_sO2", k=0.825751);
    T.Fraction respiratoryMuscle_sO2(varName="respiratoryMuscle_sO2", k=0.64629);
    T.Fraction rightHeart_sO2(varName="rightHeart_sO2", k=0.159044);
    T.Fraction skeletalMuscle_sO2(varName="skeletalMuscle_sO2", k=0.7);
    T.Fraction skin_sO2(varName="skin_sO2", k=0.736763);
    T.Fraction Bronchi_Dilution(varName="Bronchi.Dilution", k=0.938158);
    //Electrolytes
    T.pH Artys_pH1(varName="BloodPh.ArtysPh", k=7.4);
    T.pH Artys_pH_ery(varName="Artys_pH_ery", k=7.19094);
    T.pH Veins_pH(varName="BloodPh.VeinsPh", k=7.4);
    T.pH Veins_pH_ery(varName="Veins_pH_ery", k=7.17611);
    T.pH bone_pH_plasma(varName="bone_pH_plasma", k=7.28003);
    T.pH brain_pH_plasma(varName="brain_pH_plasma", k=7.36309);
    T.pH fat_pH_plasma(varName="fat_pH_plasma", k=7.45708);
    T.pH GITract_pH_plasma(varName="GITract_pH_plasma", k=7.27359);
    T.pH kidney_pH_plasma(varName="kidney_pH_plasma", k=7.14688);
    T.pH leftHeart_pH_plasma(varName="leftHeart_pH_plasma", k=7.20596);
    T.pH liver_pH_plasma(varName="liver_pH_plasma", k=7.21976);
    T.pH otherTissue_pH_plasma(varName="otherTissue_pH_plasma", k=7.26635);
    T.pH respiratoryMuscle_pH_plasma(varName="respiratoryMuscle_pH_plasma", k=7.31053);
    T.pH rightHeart_pH_plasma(varName="rightHeart_pH_plasma", k=7.18047);
    T.pH skeletalMuscle_pH_plasma(varName="skeletalMuscle_pH_plasma", k=7.49830);
    T.pH skin_pH_plasma(varName="skin_pH_plasma", k=7.35061);
    T.pH bone_pH_ery(varName="bone_pH_ery", k=7.10683);
    T.pH brain_pH_ery(varName="brain_pH_ery", k=7.17293);
    T.pH fat_pH_ery(varName="fat_pH_ery", k=7.23971);
    T.pH GITract_pH_ery(varName="GITract_pH_ery", k=7.09825);
    T.pH kidney_pH_ery(varName="kidney_pH_ery", k=6.99925);
    T.pH leftHeart_pH_ery(varName="leftHeart_pH_ery", k=7.06709);
    T.pH liver_pH_ery(varName="liver_pH_ery", k=7.06171);
    T.pH otherTissue_pH_ery(varName="otherTissue_pH_ery", k=7.09319);
    T.pH respiratoryMuscle_pH_ery(varName="respiratoryMuscle_pH_ery", k=7.13349);
    T.pH rightHeart_pH_ery(varName="rightHeart_pH_ery", k=7.04776);
    T.pH skeletalMuscle_pH_ery(varName="skeletalMuscle_pH_ery", k=7.27528);
    T.pH skin_pH_ery(varName="skin_pH_ery", k=7.16544);
    T.pH lungs_pH_plasma(varName="lungs_pH_plasma", k=7.39868);
    T.pH lungs_pH_ery(varName="lungs_pH_ery", k=7.18902);
    //Heat
    T.Temperature bone_T(varName="HeatCore.Temp(C)", k=310.15);
    T.Temperature brain_T(varName="HeatCore.Temp(C)", k=310.15);
    T.Temperature fat_T(varName="HeatCore.Temp(C)", k=310.15);
    T.Temperature GITract_T(varName="HeatCore.Temp(C)", k=310.15);
    T.Temperature kidney_T(varName="HeatCore.Temp(C)", k=310.15);
    T.Temperature leftHeart_T(varName="HeatCore.Temp(C)", k=310.15);
    T.Temperature liver_T(varName="HeatCore.Temp(C)", k=310.15);
    T.Temperature otherTissue_T(varName="HeatCore.Temp(C)", k=310.15);
    T.Temperature respiratoryMuscle_T(varName="HeatCore.Temp(C)", k=310.15);
    T.Temperature rightHeart_T(varName="HeatCore.Temp(C)", k=310.15);
    T.Temperature skeletalMuscle_T(varName="HeatCore.Temp(C)", k=310.15);
    T.Temperature skin_T(varName="HeatCore.Temp(C)", k=310.15);
    T.Temperature core_T(varName="HeatCore.Temp(C)", k=310.15);
    //Metabolism
    T.MolarFlowRate bone_CO2FromMetabolism(varName="Bone-CO2.OutflowBase", k=8.50147e-006);
    T.MolarFlowRate brain_CO2FromMetabolism(varName="Brain-CO2.OutflowBase", k=2.83333e-005);
    T.MolarFlowRate fat_CO2FromMetabolism(varName="Fat-CO2.OutflowBase", k=3.66452e-006);
    T.MolarFlowRate GITract_CO2FromMetabolism(varName="GITract-CO2.OutflowBase", k=1.11973e-005);
    T.MolarFlowRate kidney_CO2FromMetabolism(varName="Kidney-CO2.OutflowBase", k=1.20891e-005);
    T.MolarFlowRate leftHeart_CO2FromMetabolism(varName="LeftHeart-CO2.OutflowBase", k=1.57108e-005);
    T.MolarFlowRate liver_CO2FromMetabolism(varName="Liver-CO2.OutflowBase", k=1.77788e-005);
    T.MolarFlowRate otherTissue_CO2FromMetabolism(varName="OtherTissue-CO2.OutflowBase", k=4.71898e-006);
    T.MolarFlowRate respiratoryMuscle_CO2FromMetabolism(varName="RespiratoryMuscle-CO2.OutflowBase", k=3.3692e-006);
    T.MolarFlowRate rightHeart_CO2FromMetabolism(varName="RightHeart-CO2.OutflowBase", k=3.0215e-006);
    T.MolarFlowRate skeletalMuscle_CO2FromMetabolism(varName="SkeletalMuscle-CO2.OutflowBase", k=1.73808e-005);
    T.MolarFlowRate skin_CO2FromMetabolism(varName="Skin-CO2.OutflowBase", k=3.50002e-006);
  equation
    connect(CardiacOutput.y, busConnector.CardiacOutput);
    connect(AlveolarVentilated_BloodFlow.y, busConnector.AlveolarVentilated_BloodFlow);
    connect(Artys_pH1.y, busConnector.Artys_pH);
    connect(core_T.y, busConnector.core_T);
    connect(O2Veins_sO2.y, busConnector.O2Veins_sO2);
    connect(O2Artys_sO2.y, busConnector.O2Artys_sO2);
    connect(Veins_pH.y, busConnector.Veins_pH);
    connect(lungs_pH_plasma.y, busConnector.lungs_pH_plasma);
    connect(lungs_pH_ery.y, busConnector.lungs_pH_ery);
    connect(AlveolarVentilation_Env.y, busConnector.AlveolarVentilation_Env);
    connect(Bronchi_Dilution.y, busConnector.BronchiDilution);
    connect(ArtysVol.y, busConnector.ArtysVol);
    connect(VeinsVol.y, busConnector.VeinsVol);
    connect(bone_pH_plasma.y, busConnector.bone_pH_plasma);
    connect(brain_pH_plasma.y, busConnector.brain_pH_plasma);
    connect(fat_pH_plasma.y, busConnector.fat_pH_plasma);
    connect(GITract_pH_plasma.y, busConnector.GITract_pH_plasma);
    connect(kidney_pH_plasma.y, busConnector.kidney_pH_plasma);
    connect(leftHeart_pH_plasma.y, busConnector.leftHeart_pH_plasma);
    connect(liver_pH_plasma.y, busConnector.liver_pH_plasma);
    connect(otherTissue_pH_plasma.y, busConnector.otherTissue_pH_plasma);
    connect(respiratoryMuscle_pH_plasma.y, busConnector.respiratoryMuscle_pH_plasma);
    connect(rightHeart_pH_plasma.y, busConnector.rightHeart_pH_plasma);
    connect(skeletalMuscle_pH_plasma.y, busConnector.skeletalMuscle_pH_plasma);
    connect(skin_pH_plasma.y, busConnector.skin_pH_plasma);
    connect(bone_sO2.y, busConnector.bone_sO2);
    connect(brain_sO2.y, busConnector.brain_sO2);
    connect(fat_sO2.y, busConnector.fat_sO2);
    connect(GITract_sO2.y, busConnector.GITract_sO2);
    connect(kidney_sO2.y, busConnector.kidney_sO2);
    connect(leftHeart_sO2.y, busConnector.leftHeart_sO2);
    connect(liver_sO2.y, busConnector.liver_sO2);
    connect(otherTissue_sO2.y, busConnector.otherTissue_sO2);
    connect(respiratoryMuscle_sO2.y, busConnector.respiratoryMuscle_sO2);
    connect(rightHeart_sO2.y, busConnector.rightHeart_sO2);
    connect(skeletalMuscle_sO2.y, busConnector.skeletalMuscle_sO2);
    connect(skin_sO2.y, busConnector.skin_sO2);
    connect(bone_CO2FromMetabolism.y, busConnector.bone_CO2FromMetabolism);
    connect(brain_CO2FromMetabolism.y, busConnector.brain_CO2FromMetabolism);
    connect(fat_CO2FromMetabolism.y, busConnector.fat_CO2FromMetabolism);
    connect(GITract_CO2FromMetabolism.y, busConnector.GITract_CO2FromMetabolism);
    connect(kidney_CO2FromMetabolism.y, busConnector.kidney_CO2FromMetabolism);
    connect(leftHeart_CO2FromMetabolism.y, busConnector.leftHeart_CO2FromMetabolism);
    connect(liver_CO2FromMetabolism.y, busConnector.liver_CO2FromMetabolism);
    connect(otherTissue_CO2FromMetabolism.y, busConnector.otherTissue_CO2FromMetabolism);
    connect(respiratoryMuscle_CO2FromMetabolism.y, busConnector.respiratoryMuscle_CO2FromMetabolism);
    connect(rightHeart_CO2FromMetabolism.y, busConnector.rightHeart_CO2FromMetabolism);
    connect(skeletalMuscle_CO2FromMetabolism.y, busConnector.skeletalMuscle_CO2FromMetabolism);
    connect(skin_CO2FromMetabolism.y, busConnector.skin_CO2FromMetabolism);
    connect(bone_BloodFlow.y, busConnector.bone_BloodFlow);
    connect(brain_BloodFlow.y, busConnector.brain_BloodFlow);
    connect(fat_BloodFlow.y, busConnector.fat_BloodFlow);
    connect(GITract_BloodFlow.y, busConnector.GITract_BloodFlow);
    connect(kidney_BloodFlow.y, busConnector.kidney_BloodFlow);
    connect(leftHeart_BloodFlow.y, busConnector.leftHeart_BloodFlow);
    connect(otherTissue_BloodFlow.y, busConnector.otherTissue_BloodFlow);
    connect(respiratoryMuscle_BloodFlow.y, busConnector.respiratoryMuscle_BloodFlow);
    connect(rightHeart_BloodFlow.y, busConnector.rightHeart_BloodFlow);
    connect(skeletalMuscle_BloodFlow.y, busConnector.skeletalMuscle_BloodFlow);
    connect(skin_BloodFlow.y, busConnector.skin_BloodFlow);
    connect(bone_T.y, busConnector.bone_T);
    connect(brain_T.y, busConnector.brain_T);
    connect(fat_T.y, busConnector.fat_T);
    connect(GITract_T.y, busConnector.GITract_T);
    connect(kidney_T.y, busConnector.kidney_T);
    connect(leftHeart_T.y, busConnector.leftHeart_T);
    connect(liver_T.y, busConnector.liver_T);
    connect(otherTissue_T.y, busConnector.otherTissue_T);
    connect(respiratoryMuscle_T.y, busConnector.respiratoryMuscle_T);
    connect(rightHeart_T.y, busConnector.rightHeart_T);
    connect(skeletalMuscle_T.y, busConnector.skeletalMuscle_T);
    connect(skin_T.y, busConnector.skin_T);
    connect(HepaticArty_BloodFlow.y, busConnector.HepaticArty_BloodFlow);
    connect(Veins_pH_ery.y, busConnector.Veins_pH_ery);
    connect(BloodVol_Hct.y, busConnector.BloodVol_Hct);
    connect(Artys_pH_ery.y, busConnector.Artys_pH_ery);
    connect(bone_pH_ery.y, busConnector.bone_pH_ery);
    connect(brain_pH_ery.y, busConnector.brain_pH_ery);
    connect(fat_pH_ery.y, busConnector.fat_pH_ery);
    connect(GITract_pH_ery.y, busConnector.GITract_pH_ery);
    connect(kidney_pH_ery.y, busConnector.kidney_pH_ery);
    connect(leftHeart_pH_ery.y, busConnector.leftHeart_pH_ery);
    connect(liver_pH_ery.y, busConnector.liver_pH_ery);
    connect(otherTissue_pH_ery.y, busConnector.otherTissue_pH_ery);
    connect(respiratoryMuscle_pH_ery.y, busConnector.respiratoryMuscle_pH_ery);
    connect(rightHeart_pH_ery.y, busConnector.rightHeart_pH_ery);
    connect(skeletalMuscle_pH_ery.y, busConnector.skeletalMuscle_pH_ery);
    connect(skin_pH_ery.y, busConnector.skin_pH_ery);
    connect(O2Lung_sO2.y, busConnector.O2Lung_sO2);
  end Variables;
end Inputs;

model Test  
  Physiolibrary.Types.BusConnector busConnector;
  Physiomodel.Gases.CO2.CO2 carbonDioxyde;
  Inputs.Input inputs;
equation
  connect(inputs.busConnector, busConnector);
  connect(busConnector, carbonDioxyde.busConnector);
end Test;
