package Inputs
  extends Physiolibrary.Types.IO_Bus;
  redeclare model extends Variables
    //CardioVascularSystem
    T.VolumeFlowRate CardiacOutput(varName="CardiacOutput.Flow", k=9.17342e-005);
    T.VolumeFlowRate AlveolarVentilated_BloodFlow(varName="LungBloodFlow.AlveolarVentilated", k=8.98333e-005);
    T.Concentration ctHb(varName="ctHb", k=8.4); 
    T.Concentration cDPG(varName="cDPG", k=5.4);
    T.Fraction FMetHb(varName="FMetHb", k=0.005);
    T.Fraction FHbF(varName="FHbF", k=0.005);
    T.Volume ArtysVol(varName="ArtysVol.Vol", k=0.0015985);
    T.Volume VeinsVol(varName="VeinsVol.Vol", k=0.00379513);
    T.VolumeFlowRate bone_BloodFlow(varName="Bone-Flow.BloodFlow", k=5.40143e-006);
    T.VolumeFlowRate brain_BloodFlow(varName="Brain-Flow.BloodFlow", k=1.36172e-005);
    T.VolumeFlowRate fat_BloodFlow(varName="Fat-Flow.BloodFlow", k=4.01915e-006);
    T.VolumeFlowRate GITract_BloodFlow(varName="GITract-Flow.BloodFlow", k=1.9228e-005);
    T.VolumeFlowRate kidney_BloodFlow(varName="Kidney-Flow.BloodFlow", k=2.07108e-005);
    T.VolumeFlowRate leftHeart_BloodFlow(varName="LeftHeart-Flow.BloodFlow", k=3.76667e-006);
    T.VolumeFlowRate otherTissue_BloodFlow(varName="OtherTissue-Flow.BloodFlow", k=6.25202e-006);
    T.VolumeFlowRate respiratoryMuscle_BloodFlow(varName="RespiratoryMuscle-Flow.BloodFlow", k=1.63743e-006);
    T.VolumeFlowRate rightHeart_BloodFlow(varName="RightHeart-Flow.BloodFlow", k=7.08333e-007);
    T.VolumeFlowRate skeletalMuscle_BloodFlow(varName="SkeletalMuscle-Flow.BloodFlow", k=1.072e-005);
    T.VolumeFlowRate skin_BloodFlow(varName="Skin-Flow.BloodFlow", k=2.68538e-006);
    T.VolumeFlowRate HepaticArty_BloodFlow(varName="HepaticArty.Flow", k=4.10747e-006);
    //Gases
    T.Pressure CO2Artys_pCO2(varName="CO2Artys.Pressure", k=5385.4);
    T.Pressure CO2Veins_pCO2(varName="CO2Veins.Pressure", k=5977.95);
    T.Pressure CO2Lung_pCO2(varName="LungCO2.PCapy", k=5380.93);
    T.VolumeFlowRate AlveolarVentilation_Env(varName="AlveolarVentilation_Env", k=6.28222e-005);
    T.Pressure bone_pCO2(varName="Bone-CO2.PCO2", k=7911.2);
    T.Pressure brain_pCO2(varName="Brain-CO2.PCO2", k=7759.36);
    T.Pressure fat_pCO2(varName="Fat-CO2.PCO2", k=4235.52);
    T.Pressure GITract_pCO2(varName="GITract-CO2.PCO2", k=8021.73);
    T.Pressure kidney_pCO2(varName="Kidney-CO2.PCO2", k=10628);
    T.Pressure leftHeart_pCO2(varName="LeftHeart-CO2.PCO2", k=9547.2);
    T.Pressure liver_pCO2(varName="Liver-CO2.PCO2", k=9163.11);
    T.Pressure otherTissue_pCO2(varName="OtherTissue-CO2.PCO2", k=8174.3);
    T.Pressure respiratoryMuscle_pCO2(varName="RespiratoryMuscle-CO2.PCO2", k=7301.23);
    T.Pressure rightHeart_pCO2(varName="RightHeart-CO2.PCO2", k=10075.2);
    T.Pressure skeletalMuscle_pCO2(varName="SkeletalMuscle-CO2.PCO2", k=3408.73);
    T.Pressure skin_pCO2(varName="Skin-CO2.PCO2", k=6481.04);
    T.Fraction Bronchi_Dilution(varName="Bronchi.Dilution", k=0.938158);
    //Setup
    T.Pressure pCO(varName="pCO", k=0);
    //Electrolytes
    T.pH Artys_pH1(varName="BloodPh.ArtysPh", k=7.4);
    T.pH Veins_pH(varName="BloodPh.VeinsPh", k=7.4);
    T.pH bone_pH_plasma(varName="bone_pH_plasma", k=7.28003);
    T.pH brain_pH_plasma(varName="brain_pH_plasma", k=7.36309);
    T.pH fat_pH_plasma(varName="fat_pH_plasma", k=7.45708);
    T.pH GITract_pH_plasma(varName="GITract_pH_plasma", k=7.27359);
    T.pH kidney_pH_plasma(varName="kidney_pH_plasma", k=7.14688);
    T.pH leftHeart_pH_plasma(varName="leftHeart_pH_plasma", k=7.20596);
    T.pH liver_pH_plasma(varName="liver_pH_plasma", k=7.21976);
    T.pH otherTissue_pH_plasma(varName="otherTissue_pH_plasma", k=7.26635);
    T.pH respiratoryMuscle_pH_plasma(varName="respiratoryMuscle_pH_plasma", k=7.31053);
    T.pH rightHeart_pH_plasma(varName="rightHeart_pH_plasma", k=7.18047);
    T.pH skeletalMuscle_pH_plasma(varName="skeletalMuscle_pH_plasma", k=7.49830);
    T.pH skin_pH_plasma(varName="skin_pH_plasma", k=7.35061);
    T.pH lungs_pH_plasma(varName="lungs_pH_plasma", k=7.39868);
    //Heat
    T.Temperature bone_T(varName="HeatCore.Temp(C)", k=310.15);
    T.Temperature brain_T(varName="HeatCore.Temp(C)", k=310.15);
    T.Temperature fat_T(varName="HeatCore.Temp(C)", k=310.15);
    T.Temperature GITract_T(varName="HeatCore.Temp(C)", k=310.15);
    T.Temperature kidney_T(varName="HeatCore.Temp(C)", k=310.15);
    T.Temperature leftHeart_T(varName="HeatCore.Temp(C)", k=310.15);
    T.Temperature liver_T(varName="HeatCore.Temp(C)", k=310.15);
    T.Temperature otherTissue_T(varName="HeatCore.Temp(C)", k=310.15);
    T.Temperature respiratoryMuscle_T(varName="HeatCore.Temp(C)", k=310.15);
    T.Temperature rightHeart_T(varName="HeatCore.Temp(C)", k=310.15);
    T.Temperature skeletalMuscle_T(varName="HeatCore.Temp(C)", k=310.15);
    T.Temperature skin_T(varName="HeatCore.Temp(C)", k=310.15);
    T.Temperature core_T(varName="HeatCore.Temp(C)", k=310.15);
    //Metabolism
    T.MolarFlowRate bone_O2Use(varName="Bone-Flow.O2Use", storeUnit="ml_STP/min", k=1.04914e-005);
    T.MolarFlowRate brain_O2Use(varName="Brain-Flow.O2Use", storeUnit="ml_STP/min", k=2.88455e-005);
    T.MolarFlowRate fat_O2Use(varName="Fat-Flow.O2Use", storeUnit="ml_STP/min", k=4.52227e-006);
    T.MolarFlowRate GITract_O2Use(varName="GITract-Flow.O2Use", storeUnit="ml_STP/min", k=1.38182e-005);
    T.MolarFlowRate kidney_O2Use(varName="Kidney-Flow.O2Use", storeUnit="ml_STP/min", k=1.49188e-005);
    T.MolarFlowRate leftHeart_O2Use(varName="LeftHeart-Flow.O2Use", storeUnit="ml_STP/min", k=1.93881e-005);
    T.MolarFlowRate liver_O2Use(varName="Liver-Flow.O2Use", storeUnit="ml_STP/min", k=2.19404e-005);
    T.MolarFlowRate otherTissue_O2Use(varName="OtherTissue-Flow.O2Use", storeUnit="ml_STP/min", k=5.82356e-006);
    T.MolarFlowRate respiratoryMuscle_O2Use(varName="RespiratoryMuscle-Flow.O2Use", storeUnit="ml_STP/min", k=4.15784e-006);
    T.MolarFlowRate rightHeart_O2Use(varName="RightHeart-Flow.O2Use", storeUnit="ml_STP/min", k=3.72874e-006);
    T.MolarFlowRate skeletalMuscle_O2Use(varName="SkeletalMuscle-Flow.O2Use", storeUnit="ml_STP/min", k=2.14493e-005);
    T.MolarFlowRate skin_O2Use(varName="Skin-Flow.O2Use", storeUnit="ml_STP/min", k=4.31927e-006);
  equation
    connect(AlveolarVentilated_BloodFlow.y, busConnector.AlveolarVentilated_BloodFlow);
    connect(CO2Artys_pCO2.y, busConnector.CO2Artys_pCO2);
    connect(ctHb.y, busConnector.ctHb);
    connect(CardiacOutput.y, busConnector.CardiacOutput);
    connect(cDPG.y, busConnector.cDPG);
    connect(FMetHb.y, busConnector.FMetHb);
    connect(FHbF.y, busConnector.FHbF);
    connect(pCO.y, busConnector.pCO);
    connect(Artys_pH1.y, busConnector.Artys_pH);
    connect(core_T.y, busConnector.core_T);
    connect(CO2Veins_pCO2.y, busConnector.CO2Veins_pCO2);
    connect(Veins_pH.y, busConnector.Veins_pH);
    connect(CO2Lung_pCO2.y, busConnector.CO2Lung_pCO2);
    connect(lungs_pH_plasma.y, busConnector.lungs_pH_plasma);
    connect(AlveolarVentilation_Env.y, busConnector.AlveolarVentilation_Env);
    connect(Bronchi_Dilution.y, busConnector.BronchiDilution);
    connect(ArtysVol.y, busConnector.ArtysVol);
    connect(VeinsVol.y, busConnector.VeinsVol);
    connect(bone_pCO2.y, busConnector.bone_pCO2);
    connect(brain_pCO2.y, busConnector.brain_pCO2);
    connect(fat_pCO2.y, busConnector.fat_pCO2);
    connect(GITract_pCO2.y, busConnector.gitract_pCO2);
    connect(kidney_pCO2.y, busConnector.kidney_pCO2);
    connect(leftHeart_pCO2.y, busConnector.leftHeart_pCO2);
    connect(liver_pCO2.y, busConnector.liver_pCO2);
    connect(otherTissue_pCO2.y, busConnector.otherTissue_pCO2);
    connect(respiratoryMuscle_pCO2.y, busConnector.respiratoryMuscle_pCO2);
    connect(rightHeart_pCO2.y, busConnector.rightHeart_pCO2);
    connect(skeletalMuscle_pCO2.y, busConnector.skeletalMuscle_pCO2);
    connect(skin_pCO2.y, busConnector.skin_pCO2);
    connect(bone_pH_plasma.y, busConnector.bone_pH_plasma);
    connect(brain_pH_plasma.y, busConnector.brain_pH_plasma);
    connect(fat_pH_plasma.y, busConnector.fat_pH_plasma);
    connect(GITract_pH_plasma.y, busConnector.GITract_pH_plasma);
    connect(kidney_pH_plasma.y, busConnector.kidney_pH_plasma);
    connect(leftHeart_pH_plasma.y, busConnector.leftHeart_pH_plasma);
    connect(liver_pH_plasma.y, busConnector.liver_pH_plasma);
    connect(otherTissue_pH_plasma.y, busConnector.otherTissue_pH_plasma);
    connect(respiratoryMuscle_pH_plasma.y, busConnector.respiratoryMuscle_pH_plasma);
    connect(rightHeart_pH_plasma.y, busConnector.rightHeart_pH_plasma);
    connect(skeletalMuscle_pH_plasma.y, busConnector.skeletalMuscle_pH_plasma);
    connect(skin_pH_plasma.y, busConnector.skin_pH_plasma);
    connect(bone_O2Use.y, busConnector.bone_O2Use);
    connect(brain_O2Use.y, busConnector.brain_O2Use);
    connect(fat_O2Use.y, busConnector.fat_O2Use);
    connect(GITract_O2Use.y, busConnector.GITract_O2Use);
    connect(kidney_O2Use.y, busConnector.kidney_O2Use);
    connect(leftHeart_O2Use.y, busConnector.leftHeart_O2Use);
    connect(liver_O2Use.y, busConnector.liver_O2Use);
    connect(otherTissue_O2Use.y, busConnector.otherTissue_O2Use);
    connect(respiratoryMuscle_O2Use.y, busConnector.respiratoryMuscle_O2Use);
    connect(rightHeart_O2Use.y, busConnector.rightHeart_O2Use);
    connect(skeletalMuscle_O2Use.y, busConnector.skeletalMuscle_O2Use);
    connect(skin_O2Use.y, busConnector.skin_O2Use);
    connect(bone_BloodFlow.y, busConnector.bone_BloodFlow);
    connect(brain_BloodFlow.y, busConnector.brain_BloodFlow);
    connect(fat_BloodFlow.y, busConnector.fat_BloodFlow);
    connect(GITract_BloodFlow.y, busConnector.GITract_BloodFlow);
    connect(kidney_BloodFlow.y, busConnector.kidney_BloodFlow);
    connect(leftHeart_BloodFlow.y, busConnector.leftHeart_BloodFlow);
    connect(otherTissue_BloodFlow.y, busConnector.otherTissue_BloodFlow);
    connect(respiratoryMuscle_BloodFlow.y, busConnector.respiratoryMuscle_BloodFlow);
    connect(rightHeart_BloodFlow.y, busConnector.rightHeart_BloodFlow);
    connect(skeletalMuscle_BloodFlow.y, busConnector.skeletalMuscle_BloodFlow);
    connect(skin_BloodFlow.y, busConnector.skin_BloodFlow);
    connect(bone_T.y, busConnector.bone_T);
    connect(brain_T.y, busConnector.brain_T);
    connect(fat_T.y, busConnector.fat_T);
    connect(GITract_T.y, busConnector.GITract_T);
    connect(kidney_T.y, busConnector.kidney_T);
    connect(leftHeart_T.y, busConnector.leftHeart_T);
    connect(liver_T.y, busConnector.liver_T);
    connect(otherTissue_T.y, busConnector.otherTissue_T);
    connect(respiratoryMuscle_T.y, busConnector.respiratoryMuscle_T);
    connect(rightHeart_T.y, busConnector.rightHeart_T);
    connect(skeletalMuscle_T.y, busConnector.skeletalMuscle_T);
    connect(skin_T.y, busConnector.skin_T);
    connect(HepaticArty_BloodFlow.y, busConnector.HepaticArty_BloodFlow);
  end Variables;
end Inputs;

model Test  
  Physiolibrary.Types.BusConnector busConnector;
  Physiomodel.Gases.O2.O2 oxygen;
  Inputs.Input inputs;
equation
  connect(inputs.busConnector, busConnector);
  connect(busConnector, oxygen.busConnector);
end Test;
